spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/abai_cauw?reWriteBatchedInserts=true
    username: admin
    password: qwer1234
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML