spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/abai_cauw
    username: admin
    password: qwer1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # 또는 none, create, create-drop, validate 등
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML